device/urls.py
from django.urls import path

from .views import (DeviceCreateView, DeviceDeleteView,
                    DeviceDepartmentCreateView, DeviceDepartmentDeleteView,
                    DeviceDepartmentListView, DeviceDepartmentUpdateView,
                    DeviceDetailView, DeviceIPCreateView, DeviceIPDeleteView,
                    DeviceIPListView, DeviceIPUpdateView, DeviceListView,
                    DevicePortCreateView, DevicePortDeleteView,
                    DevicePortListView, DevicePortUpdateView,
                    DeviceSiteCreateView, DeviceSiteDeleteView,
                    DeviceSiteListView, DeviceSiteUpdateView,
                    DeviceStatusCreateView, DeviceStatusDeleteView,
                    DeviceStatusListView, DeviceStatusUpdateView,
                    DeviceTypeCreateView, DeviceTypeDeleteView,
                    DeviceTypeListView, DeviceTypeUpdateView, DeviceUpdateView,
                    HomeView)

urlpatterns = [
    path(
        "device-sites/",
        DeviceSiteListView.as_view(),
        name="device-site-list"
    ),

    path(
        "device-sites/create",
        DeviceSiteCreateView.as_view(),
        name="device-site-create"
    ),

    path(
        "device-sites/<int:pk>/update/",
        DeviceSiteUpdateView.as_view(),
        name="device-site-update"
    ),

    path(
        "device-sites/<int:pk>/delete/",
        DeviceSiteDeleteView.as_view(),
        name="device-site-delete"
    ),

    path(
        "device-departments/",
        DeviceDepartmentListView.as_view(),
        name="device-department-list"
    ),

    path(
        "device-departments/create",
        DeviceDepartmentCreateView.as_view(),
        name="device-department-create"
    ),

    path(
        "device-departments/<int:pk>/update/",
        DeviceDepartmentUpdateView.as_view(),
        name="device-department-update"
    ),

    path(
        "device-departments/<int:pk>/delete/",
        DeviceDepartmentDeleteView.as_view(),
        name="device-department-delete"
    ),

    path(
        "device-statuses/",
        DeviceStatusListView.as_view(),
        name="device-status-list"
    ),

    path(
        "device-statuses/create",
        DeviceStatusCreateView.as_view(),
        name="device-status-create"
    ),

    path(
        "device-statuses/<int:pk>/update/",
        DeviceStatusUpdateView.as_view(),
        name="device-status-update"
    ),

    path(
        "device-statuses/<int:pk>/delete/",
        DeviceStatusDeleteView.as_view(),
        name="device-status-delete"
    ),

    path(
        "device-types/",
        DeviceTypeListView.as_view(),
        name="device-type-list"
    ),

    path(
        "device-types/create",
        DeviceTypeCreateView.as_view(),
        name="device-type-create"
    ),

    path(
        "device-types/<int:pk>/update/",
        DeviceTypeUpdateView.as_view(),
        name="device-type-update"
    ),

    path(
        "device-types/<int:pk>/delete/",
        DeviceTypeDeleteView.as_view(),
        name="device-type-delete"
    ),

    path(
        "device-ports/",
        DevicePortListView.as_view(),
        name="device-port-list"
    ),

    path(
        "device-ports/create",
        DevicePortCreateView.as_view(),
        name="device-port-create"
    ),

    path(
        "device-ports/<int:pk>/update/",
        DevicePortUpdateView.as_view(),
        name="device-port-update"
    ),

    path(
        "device-ports/<int:pk>/delete/",
        DevicePortDeleteView.as_view(),
        name="device-port-delete"
    ),

    path(
        "device-ips/",
        DeviceIPListView.as_view(),
        name="device-ip-list"
    ),

    path(
        "device-ips/create",
        DeviceIPCreateView.as_view(),
        name="device-ip-create"
    ),

    path(
        "device-ips/<int:pk>/update/",
        DeviceIPUpdateView.as_view(),
        name="device-ip-update"
    ),

    path(
        "device-ips/<int:pk>/delete/",
        DeviceIPDeleteView.as_view(),
        name="device-ip-delete"
    ),

    path(
        "devices/",
        DeviceListView.as_view(),
        name="device-list"
    ),

    path(
        "devices/create",
        DeviceCreateView.as_view(),
        name="device-create"
    ),

    path(
        "devices/<int:pk>/detail",
        DeviceDetailView.as_view(),
        name="device-detail"
    ),

    path(
        "devices/<int:pk>/update/",
        DeviceUpdateView.as_view(),
        name="device-update"
    ),

    path(
        "devices/<int:pk>/delete/",
        DeviceDeleteView.as_view(),
        name="device-delete"
    ),
    path("", HomeView.as_view(), name="home"),

]

app_name = "device"

device_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("device.urls", namespace="device")),
     path("", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
]

user/urls.py
from django.urls import path

from user.views import (UserCreateView, UserDeleteView, UserListView,
                        UserUpdateView)

urlpatterns = [
    path(
        "users/",
        UserListView.as_view(),
        name="user-list"
    ),

    path(
        "users/create",
        UserCreateView.as_view(),
        name="user-create"
    ),

    path(
        "users/<int:pk>/update/",
        UserUpdateView.as_view(),
        name="user-update"
    ),

    path(
        "users/<int:pk>/delete/",
        UserDeleteView.as_view(),
        name="user-delete"
    ),

]


app_name = "user"

device/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q

from device.models import Device, DeviceDepartment, DeviceIP, DevicePort


class DeviceDepartmentForm(forms.ModelForm):
    site = forms.CheckboxInput()

    class Meta:
        model = DeviceDepartment
        fields = "__all__"


class DevicePortForm(forms.ModelForm):
    name = forms.IntegerField()
    site = forms.CheckboxInput()

    class Meta:
        model = DevicePort
        fields = "__all__"


class DeviceIPForm(forms.ModelForm):
    department = forms.CheckboxInput()

    class Meta:
        model = DeviceIP
        fields = "__all__"


class DeviceUpdateForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        available_ports = DevicePort.objects.filter(Q(devices__isnull=True) | Q(devices=self.instance))
        available_ip = DeviceIP.objects.filter(Q(devices__isnull=True) | Q(devices=self.instance))

        self.fields["device_ports"].queryset = available_ports
        self.fields["device_ip"].queryset = available_ip


class DeviceSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name or serial number"}
        )
    )

device/views.py
from typing import Any, Dict

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models, transaction
from django.db.models import Q
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.base import TemplateView

from device.forms import (DeviceDepartmentForm, DeviceIPForm, DevicePortForm,
                          DeviceSearchForm, DeviceUpdateForm)
from transaction.models import Transaction
from transaction.utils import create_transaction

from .models import (Device, DeviceDepartment, DeviceIP, DevicePort,
                     DeviceSite, DeviceStatus, DeviceType)


# Device Site
class DeviceSiteListView(LoginRequiredMixin, generic.ListView):
    model = DeviceSite
    template_name = "device/device_site_list.html"
    context_object_name = "device_site_list"


class DeviceSiteCreateView(LoginRequiredMixin, generic.CreateView):
    model = DeviceSite
    fields = "__all__"
    success_url = reverse_lazy("device:device-site-list")
    template_name = "device/device_site_form.html"


class DeviceSiteUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DeviceSite
    fields = "__all__"
    success_url = reverse_lazy("device:device-site-list")
    template_name = "device/device_site_form.html"


class DeviceSiteDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DeviceSite
    fields = "__all__"
    success_url = reverse_lazy("device:device-site-list")
    template_name = "device/device_site_confirm_delete.html"


# Device Department

class DeviceDepartmentListView(LoginRequiredMixin, generic.ListView):
    model = DeviceDepartment
    template_name = "device/device_department_list.html"
    context_object_name = "device_department_list"


class DeviceDepartmentCreateView(LoginRequiredMixin, generic.CreateView):
    model = DeviceDepartment
    form_class = DeviceDepartmentForm
    success_url = reverse_lazy("device:device-department-list")
    template_name = "device/device_department_form.html"


class DeviceDepartmentUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DeviceDepartment
    form_class = DeviceDepartmentForm
    success_url = reverse_lazy("device:device-department-list")
    template_name = "device/device_department_form.html"


class DeviceDepartmentDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DeviceDepartment
    success_url = reverse_lazy("device:device-department-list")
    template_name = "device/device_department_confirm_delete.html"


# Device Status
class DeviceStatusListView(LoginRequiredMixin, generic.ListView):
    model = DeviceStatus
    template_name = "device/device_status_list.html"
    context_object_name = "device_status_list"


class DeviceStatusCreateView(LoginRequiredMixin, generic.CreateView):
    model = DeviceStatus
    fields = "__all__"
    success_url = reverse_lazy("device:device-status-list")
    template_name = "device/device_status_form.html"


class DeviceStatusUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DeviceStatus
    fields = "__all__"
    success_url = reverse_lazy("device:device-status-list")
    template_name = "device/device_status_form.html"


class DeviceStatusDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DeviceStatus
    success_url = reverse_lazy("device:device-status-list")
    template_name = "device/device_status_confirm_delete.html"


# Device Type

class DeviceTypeListView(LoginRequiredMixin, generic.ListView):
    model = DeviceType
    success_url = reverse_lazy("device:device-type-list")
    template_name = "device/device_type_list.html"
    context_object_name = "device_type_list"


class DeviceTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DeviceType
    fields = "__all__"
    success_url = reverse_lazy("device:device-type-list")
    template_name = "device/device_type_form.html"


class DeviceTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DeviceType
    fields = "__all__"
    success_url = reverse_lazy("device:device-type-list")
    template_name = "device/device_type_form.html"


class DeviceTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DeviceType
    success_url = reverse_lazy("device:device-type-list")
    template_name = "device/device_type_confirm_delete.html"


# Device
class DeviceListView(LoginRequiredMixin, generic.ListView):
    model = Device
    template_name = "device/device_list.html"
    context_object_name = "device_list"
    paginate_by = 20

    def get_queryset(self):

        queryset = super().get_queryset()

        form = DeviceSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(Q(name__icontains=form.cleaned_data["name"]) | Q(
                device_serial_number__icontains=form.cleaned_data["name"]))

        status_id = self.request.GET.get("status")
        if status_id:
            status = get_object_or_404(DeviceStatus, pk=status_id)
            queryset = queryset.filter(device_status=status)

        device_type_id = self.request.GET.get("device_type")
        if device_type_id:
            device_type = get_object_or_404(DeviceType, pk=device_type_id)
            queryset = queryset.filter(device_type=device_type)

        department_id = self.request.GET.get("department")
        if department_id:
            department = get_object_or_404(DeviceDepartment, pk=department_id)
            queryset = queryset.filter(department=department)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['device_status_list'] = DeviceStatus.objects.all()
        context['device_type_list'] = DeviceType.objects.all()
        context['department_list'] = DeviceDepartment.objects.all()

        name = self.request.GET.get("name", "")
        device_serial_number = self.request.GET.get("name", "")
        context["search_form"] = DeviceSearchForm(
            initial={
                "name": name,
                "device_serial_number": device_serial_number
            }
        )
        device_type_id = self.request.session.get("device_type")
        if device_type_id:
            device_type = get_object_or_404(DeviceType, pk=device_type_id)
            context["device_type"] = device_type

        return context


class DeviceDetailView(LoginRequiredMixin, generic.DetailView):
    model = Device
    template_name = "device/device_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        device = self.get_object()

        transactions = Transaction.objects.filter(device=device)

        context['transactions'] = transactions
        return context


class DeviceCreateView(LoginRequiredMixin, generic.CreateView):
    model = Device
    fields = "__all__"
    success_url = reverse_lazy("device:device-list")
    template_name = "device/device_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['device_type'] = self.request.GET.get('device_type')  # Отримання device_type з параметрів запиту
        return context

    def get_success_url(self):
        device_type_id = self.request.session.get("device_type")
        if device_type_id:
            return reverse("device:device-list") + f"?device_type={device_type_id}"
        return reverse("device:device-list")


class DeviceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Device
    form_class = DeviceUpdateForm
    success_url = reverse_lazy("device:device-list")
    template_name = "device/device_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['device_type'] = self.request.GET.get('device_type')  # Отримання device_type з параметрів запиту
        return context

    def get_success_url(self):
        device_type_id = self.request.session.get("device_type")
        if device_type_id:
            return reverse("device:device-list") + f"?device_type={device_type_id}"
        return reverse("device:device-list")

    def form_valid(self, form):
        original_device = self.get_object()
        update_device = form.save(commit=False)  # Don't save yet

        changes = {}  # Dictionary to store changes

        for field in update_device._meta.fields:  # Loop through all fields of the model
            field_name = field.name
            old_value = getattr(original_device, field_name)
            new_value = getattr(update_device, field_name)

            if old_value != new_value:
                changes[field_name] = {
                    "old_value": old_value,
                    "new_value": new_value
                }
        device_type = form.cleaned_data.get("device_type")
        self.request.session["device_type"] = device_type.id
        original_device = update_device
        original_device.save()
        if changes:
            create_transaction(
                user=self.request.user,
                device=original_device,
                changed_fields=changes
            )

        return super().form_valid(form)


class DeviceDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Device
    success_url = reverse_lazy("device:device-list")
    template_name = "device/device_confirm_delete.html"


# Device Port
class DevicePortListView(LoginRequiredMixin, generic.ListView):
    model = DevicePort
    template_name = "device/device_port_list.html"
    context_object_name = "device_port_list"


class DevicePortCreateView(LoginRequiredMixin, generic.CreateView):
    model = DevicePort
    form_class = DevicePortForm
    success_url = reverse_lazy("device:device-port-list")
    template_name = "device/device_port_form.html"

templates/device/device_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Status</h1>

    <p style="font-size: 24px;">Are you sure you want to delete status: <strong class="text-success">{{ device }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <br>
    <a href="{% url 'device:device-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/device/device_department_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Department</h1>

    <p style="font-size: 24px;">Are you sure you want to delete site: <strong class="text-success">{{ devicedepartment }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <br>
    <a href="{% url 'device:device-department-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/device/device_department_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Departments</h1>
  {% if device_department_list %}
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Site</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
          {% for department in device_department_list %}
          <tr>
              <td>{{ department.name }}</td>
              <td>{{ department.site.name }}</td>
              <td><a class="text-info" href="{% url 'device:device-department-update' pk=department.id %}">Update</a></td>
              <td><a class="text-danger" href="{% url 'device:device-department-delete' pk=department.id %}">Delete</a></td>
          </tr>
          
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
    <p>There are no departments in Department!</p>
  {% endif %}

  <a class="button" style="float: right;" href="{% url 'device:device-department-create' %}">Create</a>

 

{% endblock %}

templates/device/device_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="title">{{ object|yesno:"Update,Create" }} Device</h1>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                <input type="hidden" name="device_type" value="{{ device_type }}">
                {{ form|crispy }}
                    <br>
                    <input class="btn btn-primary" type="submit" value="Submit">
            </form>
            <br>
            <a href="{% url 'device:device-list' %}"><button class="btn btn-secondary">Cancel</button></a>

{% endblock %}

templates/device/device_port_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Port</h1>

    <p style="font-size: 24px;">Are you sure you want to delete port: <strong class="text-success">{{ deviceport }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <br>
    <a href="{% url 'device:device-port-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/device/device_port_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="title">{{ object|yesno:"Update,Create" }} Port</h1>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                    <br>  
                    <input class="btn btn-primary" type="submit" value="Submit">
            </form>
            <br>
            <a href="{% url 'device:device-port-list' %}"><button class="btn btn-secondary">Cancel</button></a>
    
{% endblock %}

templates/device/device_port_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Ports</h1>
  {% if device_port_list %}
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Site</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
          {% for port in device_port_list %}
          <tr>
              <td>{{ port.name }}</td>
              <td>{{ port.site.name }}</td>
              <td><a class="text-info" href="{% url 'device:device-port-update' pk=port.id %}">Update</a></td>
              <td><a class="text-danger" href="{% url 'device:device-port-delete' pk=port.id %}">Delete</a></td>
          </tr>
          
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
    <p>There are no ports in Port!</p>
  {% endif %}

  <a class="button" style="float: right;" href="{% url 'device:device-port-create' %}">Create</a>

 

{% endblock %}

templates/device/device_site_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Sites</h1>
  {% if device_site_list %}
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
          {% for site in device_site_list %}
          <tr>
              <td>{{ site.name }}</td>
              <td><a class="text-info" href="{% url 'device:device-site-update' pk=site.id %}">Update</a></td>
              <td><a class="text-danger" href="{% url 'device:device-site-delete' pk=site.id %}">Delete</a></td>
          </tr>
          
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
    <p>There are no sites in Site!</p>
  {% endif %}

  <a class="button" style="float: right;" href="{% url 'device:device-site-create' %}">Create</a>

 

{% endblock %}

templates/device/device_status_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Status</h1>

    <p style="font-size: 24px;">Are you sure you want to delete status: <strong class="text-success">{{ devicestatus }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <br>
    <a href="{% url 'device:device-status-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/device/device_status_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="title">{{ object|yesno:"Update,Create" }} Status</h1>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                    <br>  
                    <input class="btn btn-primary" type="submit" value="Submit">
            </form>
            <br>
            <a href="{% url 'device:device-status-list' %}"><button class="btn btn-secondary">Cancel</button></a>
    
{% endblock %}

templates/device/device_status_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Statuses</h1>
  {% if device_status_list %}
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>

        </tr>
      </thead>
      <tbody>
          {% for status in device_status_list %}
          <tr>
              <td>{{ status.name }}</td>
             
              <td><a class="text-info" href="{% url 'device:device-status-update' pk=status.id %}">Update</a></td>
              <td><a class="text-danger" href="{% url 'device:device-status-delete' pk=status.id %}">Delete</a></td>
          </tr>
          
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
    <p>There are no statuses in Status!</p>
  {% endif %}

  <a class="button" style="float: right;" href="{% url 'device:device-status-create' %}">Create</a>

 

{% endblock %}

templates/device/device_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Type</h1>

    <p style="font-size: 24px;">Are you sure you want to delete type: <strong class="text-success">{{ devicetype }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <br>
    <a href="{% url 'device:device-type-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/device/device_type_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="title">{{ object|yesno:"Update,Create" }} Type</h1>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                    <br>  
                    <input class="btn btn-primary" type="submit" value="Submit">
            </form>
            <br>
            <a href="{% url 'device:device-type-list' %}"><button class="btn btn-secondary">Cancel</button></a>
    
{% endblock %}

templates/device/site_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Sites</h1>
  {% if site_list %}
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
          {% for site in site_list %}
          <tr>
              <td>{{ site.site }}</td>
          </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
    <p>There are no sites in Site!</p>
  {% endif %}

 

{% endblock %}