device/urls.py
from django.urls import path

from .views import (DeviceCreateView, DeviceDeleteView,
                    DeviceDepartmentCreateView, DeviceDepartmentDeleteView,
                    DeviceDepartmentListView, DeviceDepartmentUpdateView,
                    DeviceDetailView, DeviceIPCreateView, DeviceIPDeleteView,
                    DeviceIPListView, DeviceIPUpdateView, DeviceListView,
                    DevicePortCreateView, DevicePortDeleteView,
                    DevicePortListView, DevicePortUpdateView,
                    DeviceSiteCreateView, DeviceSiteDeleteView,
                    DeviceSiteListView, DeviceSiteUpdateView,
                    DeviceStatusCreateView, DeviceStatusDeleteView,
                    DeviceStatusListView, DeviceStatusUpdateView,
                    DeviceTypeCreateView, DeviceTypeDeleteView,
                    DeviceTypeListView, DeviceTypeUpdateView, DeviceUpdateView,
                    HomeView)

urlpatterns = [
    path(
        "device-sites/",
        DeviceSiteListView.as_view(),
        name="device-site-list"
    ),

    path(
        "device-sites/create",
        DeviceSiteCreateView.as_view(),
        name="device-site-create"
    ),

    path(
        "device-sites/<int:pk>/update/",
        DeviceSiteUpdateView.as_view(),
        name="device-site-update"
    ),

    path(
        "device-sites/<int:pk>/delete/",
        DeviceSiteDeleteView.as_view(),
        name="device-site-delete"
    ),

    path(
        "device-departments/",
        DeviceDepartmentListView.as_view(),
        name="device-department-list"
    ),

    path(
        "device-departments/create",
        DeviceDepartmentCreateView.as_view(),
        name="device-department-create"
    ),

    path(
        "device-departments/<int:pk>/update/",
        DeviceDepartmentUpdateView.as_view(),
        name="device-department-update"
    ),

    path(
        "device-departments/<int:pk>/delete/",
        DeviceDepartmentDeleteView.as_view(),
        name="device-department-delete"
    ),

    path(
        "device-statuses/",
        DeviceStatusListView.as_view(),
        name="device-status-list"
    ),

    path(
        "device-statuses/create",
        DeviceStatusCreateView.as_view(),
        name="device-status-create"
    ),

    path(
        "device-statuses/<int:pk>/update/",
        DeviceStatusUpdateView.as_view(),
        name="device-status-update"
    ),

    path(
        "device-statuses/<int:pk>/delete/",
        DeviceStatusDeleteView.as_view(),
        name="device-status-delete"
    ),

    path(
        "device-types/",
        DeviceTypeListView.as_view(),
        name="device-type-list"
    ),

    path(
        "device-types/create",
        DeviceTypeCreateView.as_view(),
        name="device-type-create"
    ),

    path(
        "device-types/<int:pk>/update/",
        DeviceTypeUpdateView.as_view(),
        name="device-type-update"
    ),

    path(
        "device-types/<int:pk>/delete/",
        DeviceTypeDeleteView.as_view(),
        name="device-type-delete"
    ),

    path(
        "device-ports/",
        DevicePortListView.as_view(),
        name="device-port-list"
    ),

    path(
        "device-ports/create",
        DevicePortCreateView.as_view(),
        name="device-port-create"
    ),

    path(
        "device-ports/<int:pk>/update/",
        DevicePortUpdateView.as_view(),
        name="device-port-update"
    ),

    path(
        "device-ports/<int:pk>/delete/",
        DevicePortDeleteView.as_view(),
        name="device-port-delete"
    ),

    path(
        "device-ips/",
        DeviceIPListView.as_view(),
        name="device-ip-list"
    ),

    path(
        "device-ips/create",
        DeviceIPCreateView.as_view(),
        name="device-ip-create"
    ),

    path(
        "device-ips/<int:pk>/update/",
        DeviceIPUpdateView.as_view(),
        name="device-ip-update"
    ),

    path(
        "device-ips/<int:pk>/delete/",
        DeviceIPDeleteView.as_view(),
        name="device-ip-delete"
    ),

    path(
        "devices/",
        DeviceListView.as_view(),
        name="device-list"
    ),

    path(
        "devices/create",
        DeviceCreateView.as_view(),
        name="device-create"
    ),

    path(
        "devices/<int:pk>/detail",
        DeviceDetailView.as_view(),
        name="device-detail"
    ),

    path(
        "devices/<int:pk>/update/",
        DeviceUpdateView.as_view(),
        name="device-update"
    ),

    path(
        "devices/<int:pk>/delete/",
        DeviceDeleteView.as_view(),
        name="device-delete"
    ),
    path("", HomeView.as_view(), name="home"),

]

app_name = "device"

device_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("device.urls", namespace="device")),
     path("", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
]

user/urls.py
from django.urls import path

from user.views import (UserCreateView, UserDeleteView, UserListView,
                        UserUpdateView)

urlpatterns = [
    path(
        "users/",
        UserListView.as_view(),
        name="user-list"
    ),

    path(
        "users/create",
        UserCreateView.as_view(),
        name="user-create"
    ),

    path(
        "users/<int:pk>/update/",
        UserUpdateView.as_view(),
        name="user-update"
    ),

    path(
        "users/<int:pk>/delete/",
        UserDeleteView.as_view(),
        name="user-delete"
    ),

]


app_name = "user"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
    {% endif %}
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    {% if page_obj.has_next %}
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}

<form action="" method="get">
    <div class="input-group">
      <div class="form-outline">
        {{ search_form|crispy }}
        
      </div>
      
      <button type="submit" class="btn btn-secondary">
        <i class="fa fa-search"></i>
      </button>
      
    </div>
</form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if request.user.is_authenticated %}
    <li class="list-group-item">User: <a href="">{{ request.user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout' %}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
  {% endif %}
    
      <br>
    
      <li class="list-group-item"><a href="{% url 'device:home' %}">Home</a></li>
    {% if request.user.is_superuser %}

      <li class="list-group-item"><a href="{% url 'device:device-site-list' %}">Sites</a></li>
      <li class="list-group-item"><a href="{% url 'device:device-department-list' %}">Departments</a></li>
      <li class="list-group-item"><a href="{% url 'device:device-status-list' %}">Statuses</a></li>
      <li class="list-group-item"><a href="{% url 'device:device-type-list' %}">Types</a></li>
      <li class="list-group-item"><a href="{% url 'device:device-list' %}">Devices</a></li>
      <li class="list-group-item"><a href="{% url 'device:device-port-list' %}">Ports</a></li>
      <li class="list-group-item"><a href="{% url 'device:device-ip-list' %}">IPs</a></li>

      <hr>
      <li class="list-group-item"><a href="{% url 'user:user-list' %}">Employees</a></li>
      {% else %}
        <li class="list-group-item"><a href="">My account</a></li>
      {% endif %}


    </ul>