device_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("device.urls", namespace="device")),
     path("", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
]

user/urls.py
from django.urls import path

from user.views import (UserCreateView, UserDeleteView, UserListView,
                        UserUpdateView)

urlpatterns = [
    path(
        "users/",
        UserListView.as_view(),
        name="user-list"
    ),

    path(
        "users/create",
        UserCreateView.as_view(),
        name="user-create"
    ),

    path(
        "users/<int:pk>/update/",
        UserUpdateView.as_view(),
        name="user-update"
    ),

    path(
        "users/<int:pk>/delete/",
        UserDeleteView.as_view(),
        name="user-delete"
    ),

]


app_name = "user"

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from device.models import DeviceSite


# Create your models here.
class User(AbstractUser):
    site = models.ManyToManyField(DeviceSite, related_name="user")
    class Meta:
        ordering = ["username"]

    def __str__(self):
        return self.username
    
    def get_absolute_url(self): # new
        return reverse("user:user-list")

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from device.models import DeviceSite
from user.models import User


class UserCreationForm(UserCreationForm):
    site = forms.ModelMultipleChoiceField(
        queryset=DeviceSite.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + (
             "email",  "site"
        )


class UserUpdateForm(forms.ModelForm):
    site = forms.ModelMultipleChoiceField(
        queryset=DeviceSite.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    new_password = forms.CharField(widget=forms.PasswordInput, required=False)  # New password field
    class Meta:
        model = User
        fields = ["username", "site", "new_password"]


class UserSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )

user/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from user.models import User

from .forms import UserCreationForm, UserSearchForm, UserUpdateForm

# Create your views here.


class UserListView(LoginRequiredMixin, generic.ListView):
    model = User
    paginate_by = 10


    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")
        context["search_form"] = UserSearchForm(
            initial={
                "username": username
            }
        )
        return context

    def get_queryset(self):
        queryset = User.objects.all()
        form = UserSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset



class UserCreateView(LoginRequiredMixin, generic.CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("user:user-list")


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm


    def form_valid(self, form):
        user = form.save(commit=False)

        user.username = form.cleaned_data['username']
        user.site.set(form.cleaned_data['site'])  # Update many-to-many relationship

        new_password = form.cleaned_data['new_password']
        if new_password:
            user.set_password(new_password)
            # self.request.user = user
            update_session_auth_hash(self.request, user)  # Update session to prevent logout

        user.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return self.object.get_absolute_url() 


class UserDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = User
    success_url = reverse_lazy("user:user-list")

templates/user/user_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Employee</h1>

    <p style="font-size: 24px;">Are you sure you want to user: <strong class="text-success">{{ user }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <br>
    <a href="{% url 'user:user-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/user/user_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="title">{{ object|yesno:"Update,Create" }} Employee</h1>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                
                    <input class="btn btn-primary" type="submit" value="Submit">
            </form>
            <br>
            
           <div style="display: flex; justify-content: space-between">
             <a href="{% url 'user:user-list' %}"><button class="btn btn-secondary">Cancel</button></a>
            <button class="btn btn-warning"  id="toggle-password" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
              </svg></button>
           </div>



            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const toggleButton = document.getElementById('toggle-password');
                    const passwordInputs = document.querySelectorAll('[type="password"]');
                    
                    toggleButton.addEventListener('click', function() {
                        passwordInputs.forEach(input => {
                            if (input.type === 'password') {
                                input.type = 'text';
                            } else {
                                input.type = 'password';
                            }
                        });
                    });
                });
            </script>
{% endblock %}

templates/user/user_list.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">
        Workers
      </h1>

      {% block search_form %}
        {% include "includes/search_form.html" %}
      {% endblock %}

      {% if user_list %}
      <div class="table-responsive">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th>Username</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
              {% for employee in user_list %}
              <tr>
                  <td><a class="text-dark" href="">{{ employee.username }}</a></td>
                  <td><a class="text-info" href="{% url 'user:user-update' pk=employee.id %}">Update</a></td>
                  <td><a style="color: rgb(252, 61, 3);" href="{% url 'user:user-delete' pk=employee.id %}">Delete</a></td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
        
          
        {% else %}
        <p>The are no user in Employees</p>
        {% endif %}
        <a class="button" style="float: right;" href="{% url 'user:user-create' %}">Create</a>

{% endblock %}